#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const ROOT_DIR = process.cwd();
const TIERS = ['primitives', 'domain', 'features', 'compositions', 'templates'];

function scanPatterns() {
  const patterns = [];

  for (const tier of TIERS) {
    const tierPath = path.join(ROOT_DIR, tier);
    if (!fs.existsSync(tierPath)) continue;

    scanDir(tierPath, tier, patterns);
  }

  return patterns;
}

function scanDir(dir, tier, list) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const rel = path.relative(ROOT_DIR, dir);

  const hasReadme = entries.some(e => e.isFile() && e.name.toLowerCase() === 'readme.md');
  const isTierRoot = rel === tier;

  if (!isTierRoot && hasReadme) {
    const readmeContent = fs.readFileSync(path.join(dir, 'README.md'), 'utf-8');
    const name = path.basename(dir);

    let status = 'EXPERIMENTAL';
    const statusMatch = readmeContent.match(/\[(PROVEN|VALIDATED|EXPERIMENTAL|DEPRECATED)\]/i);
    if (statusMatch) status = statusMatch[1].toUpperCase();

    let version = '1.0';
    const vMatch = readmeContent.match(/v(\d+(\.\d+)*)/i);
    if (vMatch) version = vMatch[1];

    const files = entries.filter(e => e.isFile() && !e.name.startsWith('.')).map(e => e.name);

    list.push({
      name,
      path: rel,
      tier,
      status,
      version,
      files,
    });
  }

  for (const entry of entries) {
    if (entry.isDirectory() && !entry.name.startsWith('.') && entry.name !== 'node_modules') {
      scanDir(path.join(dir, entry.name), tier, list);
    }
  }
}

function updateIndex() {
  const patterns = scanPatterns();
  const indexPath = path.join(ROOT_DIR, 'INDEX.md');

  let existing = '';
  if (fs.existsSync(indexPath)) {
    existing = fs.readFileSync(indexPath, 'utf-8');
  }

  const proven = patterns.filter(p => p.status === 'PROVEN');
  const validated = patterns.filter(p => p.status === 'VALIDATED');
  const experimental = patterns.filter(p => p.status === 'EXPERIMENTAL');

  let out = `# Knowledge Index\n\n> Read this FIRST. Auto-generated by \`quiv\`.\n\n`;

  // Quick nav
  out += `## Quick Navigation\n\n### By Status\n`;
  out += `- **PROVEN** (3+ deployments): ${proven.length ? proven.map(p => `\`${p.path}\``).join(', ') : '_(none yet)_'}\n`;
  out += `- **VALIDATED** (1-2 deployments): ${validated.length ? validated.map(p => `\`${p.path}\``).join(', ') : '_(none yet)_'}\n`;
  out += `- **EXPERIMENTAL** (new): ${experimental.length ? experimental.map(p => `\`${p.path}\``).join(', ') : '_(none yet)_'}\n\n`;

  out += `## Pattern Catalog\n\n`;

  for (const tier of TIERS) {
    const tierP = patterns.filter(p => p.tier === tier);
    const title = tier.charAt(0).toUpperCase() + tier.slice(1);
    out += `### ${title}\n| Pattern | Path | Status | Details |\n|---|---|---|---|\n`;
    if (tierP.length === 0) {
      out += `| _(empty)_ | \`${tier}/\` | - | - |\n\n`;
    } else {
      for (const p of tierP) {
        out += `| **${p.name}** | \`${p.path}\` | \`${p.status}\` | v${p.version} |\n`;
      }
      out += '\n';
    }
  }

  fs.writeFileSync(indexPath, out.trim() + '\n', 'utf-8');
  console.log(`✓ Successfully updated INDEX.md with ${patterns.length} patterns.`);
}

updateIndex();
