import fs from 'node:fs';
import type { Pattern, Tier } from './types.js';
import { TIERS } from './types.js';

export interface ParsedIndexSection {
  title: string;
  items: Array<{
    pattern: string;
    path: string;
    status?: string;
    extra?: string;
  }>;
}

export function parseIndexFile(indexPath: string): {
  quickNav: string[];
  sections: Record<string, ParsedIndexSection>;
} {
  const result: {
    quickNav: string[];
    sections: Record<string, ParsedIndexSection>;
  } = {
    quickNav: [],
    sections: {},
  };

  if (!fs.existsSync(indexPath)) {
    return result;
  }

  const content = fs.readFileSync(indexPath, 'utf-8');
  const lines = content.split('\n');

  let inQuickNav = false;
  let currentSection = '';

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed.startsWith('## Quick Navigation')) {
      inQuickNav = true;
      continue;
    }

    if (inQuickNav) {
      if (trimmed.startsWith('## ') && !trimmed.startsWith('## Quick Navigation')) {
        inQuickNav = false;
      } else if (trimmed.startsWith('- **') || trimmed.startsWith('- [')) {
        result.quickNav.push(trimmed);
      }
    }

    if (trimmed.startsWith('### ')) {
      currentSection = trimmed.replace('### ', '').trim().toLowerCase();
      if (!result.sections[currentSection]) {
        result.sections[currentSection] = {
          title: trimmed.replace('### ', '').trim(),
          items: [],
        };
      }
      continue;
    }

    // Parse markdown table rows: | Name | Path | Status | ... |
    if (currentSection && trimmed.startsWith('|') && !trimmed.includes('---') && !trimmed.toLowerCase().includes('| pattern |') && !trimmed.toLowerCase().includes('| template |')) {
      const parts = trimmed
        .split('|')
        .map((p) => p.trim())
        .filter((p) => p.length > 0);

      if (parts.length >= 2) {
        const pattern = parts[0].replace(/\[|\]/g, '');
        const pathVal = parts[1];
        const status = parts[2];
        const extra = parts.slice(3).join(' | ');

        if (pathVal && !pathVal.includes('(to be filled')) {
          result.sections[currentSection].items.push({
            pattern,
            path: pathVal,
            status,
            extra,
          });
        }
      }
    }
  }

  return result;
}

export function generateIndexMarkdown(patterns: Pattern[], existingContent?: string): string {
  // Categorize patterns by tier
  const tierPatterns: Record<Tier, Pattern[]> = {
    primitives: [],
    domain: [],
    features: [],
    compositions: [],
    templates: [],
  };

  for (const p of patterns) {
    if (tierPatterns[p.tier]) {
      tierPatterns[p.tier].push(p);
    }
  }

  // Count proven, validated, experimental
  const proven = patterns.filter((p) => (p.metadata.status || 'EXPERIMENTAL') === 'PROVEN');
  const validated = patterns.filter((p) => (p.metadata.status || 'EXPERIMENTAL') === 'VALIDATED');
  const experimental = patterns.filter((p) => (p.metadata.status || 'EXPERIMENTAL') === 'EXPERIMENTAL');

  let header = `# Knowledge Index\n\n> Read this FIRST. Auto-generated by \`quiv\`.\n\n`;

  // Preserve custom quick navigation if existing
  let quickNavSection = `## Quick Navigation\n\n### By Problem\n- **Offline/Sync**: features/offline-sync, primitives/hooks/useOfflineEntity\n- **Data Models**: domain/erp/inventory/data-models\n- **UI Components**: primitives/ui\n- **PWA / Apple Styling**: compositions/pwa-apple\n- **Project Start**: templates/nextjs-pwa\n\n### By Status\n- **PROVEN** (3+ deployments): ${proven.length > 0 ? proven.map((p) => `\`${p.path}\``).join(', ') : '_(none yet)_'}\n- **VALIDATED** (1-2 deployments): ${validated.length > 0 ? validated.map((p) => `\`${p.path}\``).join(', ') : '_(none yet)_'}\n- **EXPERIMENTAL** (new): ${experimental.length > 0 ? experimental.map((p) => `\`${p.path}\``).join(', ') : '_(none yet)_'}\n`;

  if (existingContent && existingContent.includes('## Quick Navigation')) {
    const qMatch = existingContent.match(/## Quick Navigation[\s\S]*?(?=\n## Pattern Catalog|\n### Primitives|$)/);
    if (qMatch) {
      // Keep existing quick nav but update status line
      quickNavSection = qMatch[0].trim() + '\n';
    }
  }

  let catalog = `\n## Pattern Catalog\n\n`;

  // Primitives
  catalog += `### Primitives\n| Pattern | Path | Status | Depends On |\n|---------|------|--------|------------|\n`;
  if (tierPatterns.primitives.length === 0) {
    catalog += `| _(empty)_ | primitives/ | - | - |\n`;
  } else {
    for (const p of tierPatterns.primitives) {
      const deps = (p.metadata.depends_on || []).join(', ') || '-';
      catalog += `| **${p.name}** | \`${p.path}\` | \`${p.metadata.status || 'EXPERIMENTAL'}\` | ${deps} |\n`;
    }
  }

  // Domain
  catalog += `\n### Domain\n| Pattern | Path | Status | Business Area |\n|---------|------|--------|---------------|\n`;
  if (tierPatterns.domain.length === 0) {
    catalog += `| _(empty)_ | domain/ | - | - |\n`;
  } else {
    for (const p of tierPatterns.domain) {
      const area = p.metadata.domain || p.path.split('/')[1] || '-';
      catalog += `| **${p.name}** | \`${p.path}\` | \`${p.metadata.status || 'EXPERIMENTAL'}\` | ${area} |\n`;
    }
  }

  // Features
  catalog += `\n### Features\n| Pattern | Path | Status | Includes |\n|---------|------|--------|----------|\n`;
  if (tierPatterns.features.length === 0) {
    catalog += `| _(empty)_ | features/ | - | - |\n`;
  } else {
    for (const p of tierPatterns.features) {
      const inc = p.files.filter((f) => !f.toLowerCase().includes('readme')).join(', ') || 'implementation';
      catalog += `| **${p.name}** | \`${p.path}\` | \`${p.metadata.status || 'EXPERIMENTAL'}\` | ${inc} |\n`;
    }
  }

  // Compositions
  catalog += `\n### Compositions\n| Pattern | Path | Status | Requires |\n|---------|------|--------|----------|\n`;
  if (tierPatterns.compositions.length === 0) {
    catalog += `| _(empty)_ | compositions/ | - | - |\n`;
  } else {
    for (const p of tierPatterns.compositions) {
      const req = (p.metadata.depends_on || []).join(', ') || '-';
      catalog += `| **${p.name}** | \`${p.path}\` | \`${p.metadata.status || 'EXPERIMENTAL'}\` | ${req} |\n`;
    }
  }

  // Templates
  catalog += `\n### Templates\n| Template | Path | Status | Stack |\n|----------|------|--------|-------|\n`;
  if (tierPatterns.templates.length === 0) {
    catalog += `| _(empty)_ | templates/ | - | - |\n`;
  } else {
    for (const p of tierPatterns.templates) {
      const stack = (p.metadata.tags || []).join(', ') || 'starter';
      catalog += `| **${p.name}** | \`${p.path}\` | \`${p.metadata.status || 'EXPERIMENTAL'}\` | ${stack} |\n`;
    }
  }

  return header + quickNavSection + catalog;
}
