#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Intelligently find knowledge root directory
const KNOWLEDGE_DIR = fs.existsSync(path.join(process.cwd(), 'primitives'))
  ? process.cwd()
  : fs.existsSync(path.join(process.cwd(), 'knowledge/primitives'))
  ? path.join(process.cwd(), 'knowledge')
  : path.resolve(__dirname, '..');

const TIERS = ['primitives', 'domain', 'features', 'compositions', 'templates'];

// Parse arguments
const args = process.argv.slice(2);
const isCheckMode = args.includes('--check');
const outputIdx = args.indexOf('--output');
const outputPath = outputIdx !== -1 && args[outputIdx + 1] ? path.resolve(args[outputIdx + 1]) : path.join(KNOWLEDGE_DIR, 'INDEX.md');

function scanPatterns() {
  const patterns = [];

  for (const tier of TIERS) {
    const tierPath = path.join(KNOWLEDGE_DIR, tier);
    if (!fs.existsSync(tierPath)) continue;

    scanDir(tierPath, tier, patterns);
  }

  return patterns;
}

function scanDir(dir, tier, list) {
  const baseName = path.basename(dir);
  if (baseName.startsWith('_') || baseName === 'examples' || baseName === 'node_modules' || baseName === 'dist' || baseName === '.git') {
    return;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const rel = path.relative(KNOWLEDGE_DIR, dir);

  const hasReadme = entries.some(e => e.isFile() && e.name.toLowerCase() === 'readme.md');
  const isTierRoot = rel === tier;

  if (!isTierRoot && hasReadme) {
    const readmeContent = fs.readFileSync(path.join(dir, 'README.md'), 'utf-8');
    
    // Check for YAML frontmatter with `name:`
    const frontmatterMatch = readmeContent.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (frontmatterMatch) {
      const fContent = frontmatterMatch[1];
      const nameMatch = fContent.match(/^name:\s*([^\r\n]+)/m);
      if (nameMatch) {
        const name = nameMatch[1].trim();

        let status = 'EXPERIMENTAL';
        const statusMatch = fContent.match(/^status:\s*([^\r\n]+)/m);
        if (statusMatch) status = statusMatch[1].trim().toUpperCase();

        let version = '1.0';
        const vMatch = fContent.match(/^version:\s*["']?([^"'\r\n]+)["']?/m);
        if (vMatch) version = vMatch[1].trim();

        const files = entries.filter(e => e.isFile() && !e.name.startsWith('.')).map(e => e.name);

        list.push({
          name,
          path: rel,
          tier,
          status,
          version,
          files,
        });
      }
    }
  }

  for (const entry of entries) {
    if (entry.isDirectory() && !entry.name.startsWith('.') && !entry.name.startsWith('_') && entry.name !== 'node_modules' && entry.name !== 'examples') {
      scanDir(path.join(dir, entry.name), tier, list);
    }
  }
}

function generateIndex() {
  const patterns = scanPatterns();
  const proven = patterns.filter(p => p.status === 'PROVEN');
  const validated = patterns.filter(p => p.status === 'VALIDATED');
  const experimental = patterns.filter(p => p.status === 'EXPERIMENTAL');

  let out = `# Knowledge Index\n\n> Read this FIRST. Auto-generated by \`quiv\`.\n\n`;

  // Quick nav
  out += `## Quick Navigation\n\n### By Status\n`;
  out += `- **PROVEN** (3+ deployments): ${proven.length ? proven.map(p => `\`${p.path}\``).join(', ') : '_(none yet)_'}\n`;
  out += `- **VALIDATED** (1-2 deployments): ${validated.length ? validated.map(p => `\`${p.path}\``).join(', ') : '_(none yet)_'}\n`;
  out += `- **EXPERIMENTAL** (new): ${experimental.length ? experimental.map(p => `\`${p.path}\``).join(', ') : '_(none yet)_'}\n\n`;

  out += `## Pattern Catalog\n\n`;

  for (const tier of TIERS) {
    const tierP = patterns.filter(p => p.tier === tier);
    const title = tier.charAt(0).toUpperCase() + tier.slice(1);
    out += `### ${title}\n| Pattern | Path | Status | Details |\n|---|---|---|---|\n`;
    if (tierP.length === 0) {
      out += `| _(empty)_ | \`${tier}/\` | - | - |\n\n`;
    } else {
      for (const p of tierP) {
        out += `| **${p.name}** | \`${p.path}\` | \`${p.status}\` | v${p.version} |\n`;
      }
      out += '\n';
    }
  }

  return { content: out.trim() + '\n', count: patterns.length };
}

const { content: newContent, count } = generateIndex();

if (isCheckMode) {
  let existingContent = '';
  if (fs.existsSync(outputPath)) {
    existingContent = fs.readFileSync(outputPath, 'utf-8');
  }

  if (existingContent.trim() !== newContent.trim()) {
    console.error(`::error::INDEX.md is out of date (${count} patterns indexed). Run 'node scripts/update-index.js' locally and commit.`);
    process.exit(1);
  } else {
    console.log(`✓ INDEX.md is up to date (${count} patterns verified).`);
    process.exit(0);
  }
} else {
  fs.writeFileSync(outputPath, newContent, 'utf-8');
  console.log(`✓ Successfully updated ${path.relative(process.cwd(), outputPath)} with ${count} patterns.`);
}
